/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LMS;

import java.util.ArrayList;

/**
 *
 * @author abdul
 */
public class Libranian extends CheckoutClerk {

    /**
     * Creates new form Libranian
     */
    public Libranian() {
        super();
        initComponents();
        
    }
    public void initializeLibranian(){

        super.initializeCheckoutClerk();
        jMenuBar2 = new javax.swing.JMenuBar();
        View = new javax.swing.JMenu();
        personalProfile_menuItem = new javax.swing.JMenuItem();
        borrowed_menuItem = new javax.swing.JMenuItem();
        borrowerProfile_menuItem = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        editInfo_menuItem = new javax.swing.JMenuItem();
        Add = new javax.swing.JMenu();
        newBorrower_menuItem = new javax.swing.JMenuItem();
        NewItem_menuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        View.setText("View");

        personalProfile_menuItem.setText("Personal Profile");
        personalProfile_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalProfile_menuItemActionPerformed(evt);
            }
        });
        View.add(personalProfile_menuItem);

        borrowed_menuItem.setText("List of items currently borrowed by ...");
        borrowed_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowed_menuItemActionPerformed(evt);
            }
        });
        View.add(borrowed_menuItem);

        borrowerProfile_menuItem.setText("Profile of a Borrower");
        borrowerProfile_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowerProfile_menuItemActionPerformed(evt);
            }
        });
        View.add(borrowerProfile_menuItem);

        jMenuBar2.add(View);

        Edit.setText("Edit");

        editInfo_menuItem.setText("A borrower's personal info");
        editInfo_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editInfo_menuItemActionPerformed(evt);
            }
        });
        Edit.add(editInfo_menuItem);

        Add.setText("Add");

        newBorrower_menuItem.setText("New Borrower");
        newBorrower_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBorrower_menuItemActionPerformed(evt);
            }
        });
        Add.add(newBorrower_menuItem);

        NewItem_menuItem.setText("New Item");
        NewItem_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewItem_menuItemActionPerformed(evt);
            }
        });
        Add.add(NewItem_menuItem);

        Edit.add(Add);

        jMenu1.setText("Delete");

        jMenuItem1.setText("Existing Item");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        Edit.add(jMenu1);

        jMenuBar2.add(Edit);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 773, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        pack();
    }
    public Libranian(String nam,String i,String tel,String add,String Em)
    {
        super(nam,i,tel,add,Em);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        View = new javax.swing.JMenu();
        personalProfile_menuItem = new javax.swing.JMenuItem();
        borrowed_menuItem = new javax.swing.JMenuItem();
        borrowerProfile_menuItem = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        editInfo_menuItem = new javax.swing.JMenuItem();
        Add = new javax.swing.JMenu();
        newBorrower_menuItem = new javax.swing.JMenuItem();
        NewItem_menuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        View.setText("View");

        personalProfile_menuItem.setText("Personal Profile");
        personalProfile_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalProfile_menuItemActionPerformed(evt);
            }
        });
        View.add(personalProfile_menuItem);

        borrowed_menuItem.setText("List of items currently borrowed by ...");
        borrowed_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowed_menuItemActionPerformed(evt);
            }
        });
        View.add(borrowed_menuItem);

        borrowerProfile_menuItem.setText("Profile of a Borrower");
        borrowerProfile_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowerProfile_menuItemActionPerformed(evt);
            }
        });
        View.add(borrowerProfile_menuItem);

        jMenuBar2.add(View);

        Edit.setText("Edit");

        editInfo_menuItem.setText("A borrower's personal info");
        editInfo_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editInfo_menuItemActionPerformed(evt);
            }
        });
        Edit.add(editInfo_menuItem);

        Add.setText("Add");

        newBorrower_menuItem.setText("New Borrower");
        newBorrower_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBorrower_menuItemActionPerformed(evt);
            }
        });
        Add.add(newBorrower_menuItem);

        NewItem_menuItem.setText("New Item");
        NewItem_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewItem_menuItemActionPerformed(evt);
            }
        });
        Add.add(NewItem_menuItem);

        Edit.add(Add);

        jMenu1.setText("Delete");

        jMenuItem1.setText("Existing Item");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        Edit.add(jMenu1);

        jMenuBar2.add(Edit);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personalProfile_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalProfile_menuItemActionPerformed
        // TODO add your handling code here:
        PersonalInfo info=new PersonalInfo(this);
        info.setVisible(true);
        info.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }//GEN-LAST:event_personalProfile_menuItemActionPerformed

    private void borrowed_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowed_menuItemActionPerformed
        // TODO add your handling code here:

        BorrowedBy bor=new BorrowedBy();
        bor.setVisible(true);
        bor.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

    }//GEN-LAST:event_borrowed_menuItemActionPerformed

    private void borrowerProfile_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowerProfile_menuItemActionPerformed
        // TODO add your handling code here:
        BorrowerName bname= new BorrowerName();
        bname.setVisible(true);
        bname.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

    }//GEN-LAST:event_borrowerProfile_menuItemActionPerformed

    private void newBorrower_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBorrower_menuItemActionPerformed
        // TODO add your handling code here:

        AddNewBorrower temp= new AddNewBorrower();
        temp.setVisible(true);
        temp.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }//GEN-LAST:event_newBorrower_menuItemActionPerformed

    private void editInfo_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editInfo_menuItemActionPerformed
        // TODO add your handling code here:
        EditInfoName temp= new EditInfoName();
        temp.setVisible(true);
        temp.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }//GEN-LAST:event_editInfo_menuItemActionPerformed

    private void NewItem_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewItem_menuItemActionPerformed
        // TODO add your handling code here:
        AddNewItem temp=new AddNewItem();
        temp.setVisible(true);
        temp.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }//GEN-LAST:event_NewItem_menuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
       super.Users=super.renewUser();
       super.Items=super.renewItem();
       super.loan=super.renewLoan();
        
        DeleteItem temp=new DeleteItem();
        temp.setVisible(true);
        temp.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Libranian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Libranian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Libranian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Libranian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Libranian().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Add;
    private javax.swing.JMenu Edit;
    private javax.swing.JMenuItem NewItem_menuItem;
    private javax.swing.JMenu View;
    private javax.swing.JMenuItem borrowed_menuItem;
    private javax.swing.JMenuItem borrowerProfile_menuItem;
    private javax.swing.JMenuItem editInfo_menuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem newBorrower_menuItem;
    private javax.swing.JMenuItem personalProfile_menuItem;
    // End of variables declaration//GEN-END:variables

    public void CheckOutItem(String ItemName,String UserName)
    {
        super.CheckOutItem(ItemName, UserName);
    }
    public void CheckInItem(String ItemName,String UserName)
    {
        super.CheckInItem(ItemName, UserName);
    }
     public void RenewItem(String ItemName,String UserName)
    {
        super.RenewItem(ItemName, UserName);
    }
   public ArrayList<Item> SearchTitle(String title)
   {
       return super.SearchTitle(title);
   }
   public ArrayList<Item> SearchAuthor(String author)
   {
       return super.SearchAuthor(author);
   }
   public ArrayList<Item> SearchSubject(String Subject)
   {
         return super.SearchSubject(Subject);
   }
   public ArrayList<String> currentlyBorrowed(String name)
   {
     return super.currentlyBorrowed(name);
   }
   public ArrayList<String> getAllTitle()
   {
       ArrayList<String> temp=new ArrayList<>();
       for (int i = 0; i <super.Items.size(); i++)
       {
           temp.add(super.Items.get(i).Title);
       }
       return temp;
   }
   public void deleteItem(String name)
   {
       for (int i = 0; i <super.Items.size(); i++)
       {
           if(super.Items.get(i).Title.equals(name))
           {
               super.Items.remove(i);
           }
       }
   }


}
