package LMS;

import LMS.Borrower;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author abdul
 */
public class Login extends Management {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcome = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        uname_field = new javax.swing.JTextField();
        password_field = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        welcome.setText("Welcome to LMS!");
        welcome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        username.setText("Enter username:");

        password.setText("Enter Password:");

        uname_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uname_fieldActionPerformed(evt);
            }
        });

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(welcome)
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(login)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(uname_field)
                            .addComponent(password_field, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username)
                    .addComponent(uname_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password)
                    .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(login)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        //password=1234
//        if (this.uname_field.getText().equals("borrower") && this.password_field.getText().equals("1234")) {
//            Borrower borrower = new Borrower();
//            borrower.setName("Shakoor");
//            borrower.setEmail("shakoor@gmail.com");
//            borrower.setAddress("6-Shakoor town");
//            borrower.setTel("112233");
//            borrower.initializeBorrower();
//            borrower.setVisible(true);
//            this.dispose();
//        } else if (this.uname_field.getText().equals("clerk") && this.password_field.getText().equals("1234")) {
//            CheckoutClerk clerk = new CheckoutClerk();
//            clerk.setName("clerk");
//            clerk.setEmail("clerk@email");
//            clerk.setAddress("clerk land");
//            clerk.setTel("3334445");
//            clerk.initializeCheckoutClerk();
//            clerk.setVisible(true);
//            this.dispose();
//        } else if (this.uname_field.getText().equals("lib") && this.password_field.getText().equals("1234")) {
//            Libranian lib = new Libranian();
//            lib.initializeLibranian();
//            lib.setVisible(true);
//            this.dispose();
//        } else if (this.uname_field.getText().equals("") && this.password_field.getText().equals("")) {
//            Libranian lib = new Libranian();
//            lib.initializeLibranian();
//            lib.setVisible(true);
//            this.dispose();
//        } 
            if (this.uname_field.getText().equals("Aamir Raheem") && this.password_field.getText().equals("1234")) {
            super.Users = super.renewUser();
            super.Items = super.renewItem();
            super.loan = super.renewLoan();
            Libranian lib = new Libranian();
            for (int i = 0; i < Users.size(); i++) {
                if (Users.get(i).name.equals(this.uname_field.getText())) {
                    lib.Email = Users.get(i).Email;
                    lib.name = Users.get(i).name;
                    lib.password = Users.get(i).password;
                    lib.address = Users.get(i).address;
                    lib.telephone = Users.get(i).telephone;

                }
            }
            super.Users.add(lib);
            lib.initializeLibranian();

            lib.setVisible(true);
            this.dispose();
        } else if (this.uname_field.getText().equals("Farwa Batool") && this.password_field.getText().equals("1234")) {

            super.Users = super.renewUser();
            super.Items = super.renewItem();
            super.loan = super.renewLoan();

            CheckoutClerk clerk = new CheckoutClerk();
            for (int i = 0; i < Users.size(); i++) {
                if (Users.get(i).name.equals(this.uname_field.getText())) {
                    clerk.Email = Users.get(i).Email;
                    clerk.name = Users.get(i).name;
                    clerk.password = Users.get(i).password;
                    clerk.address = Users.get(i).address;
                    clerk.telephone = Users.get(i).telephone;

                }
            }
            super.Users.add(clerk);
            clerk.initializeCheckoutClerk();

            clerk.setVisible(true);
            this.dispose();
        }
             else if (super.checkLogin(this.uname_field.getText(), this.password_field.getText())) {
            super.Users = super.renewUser();
            super.Items = super.renewItem();
            super.loan = super.renewLoan();
            Borrower b = new Borrower();
            for (int i = 0; i < Users.size(); i++) {
                if (Users.get(i).name.equals(this.uname_field.getText())) {

                    b.Email = Users.get(i).Email;
                    b.name = Users.get(i).name;
                    b.password = Users.get(i).password;
                    b.address = Users.get(i).address;
                    b.telephone = Users.get(i).telephone;
                }
            }

            b.initializeBorrower();

            b.setVisible(true);
            this.dispose();

        }
                    else {
            JOptionPane.showMessageDialog(login, "Unsuccessfull :(");
        }


    }//GEN-LAST:event_loginActionPerformed

    private void uname_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uname_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uname_fieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton login;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JTextField uname_field;
    private javax.swing.JLabel username;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
}
